// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	comment "sosmedapps/features/comment"

	mock "github.com/stretchr/testify/mock"
)

// CommentService is an autogenerated mock type for the CommentService type
type CommentService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: token
func (_m *CommentService) Delete(token interface{}) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewComment provides a mock function with given fields: token, NewComment
func (_m *CommentService) NewComment(token interface{}, NewComment comment.Core) (comment.Core, error) {
	ret := _m.Called(token, NewComment)

	var r0 comment.Core
	if rf, ok := ret.Get(0).(func(interface{}, comment.Core) comment.Core); ok {
		r0 = rf(token, NewComment)
	} else {
		r0 = ret.Get(0).(comment.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, comment.Core) error); ok {
		r1 = rf(token, NewComment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCommentService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentService creates a new instance of CommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentService(t mockConstructorTestingTNewCommentService) *CommentService {
	mock := &CommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
