// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	comment "sosmedapps/features/comment"

	mock "github.com/stretchr/testify/mock"
)

// CommentData is an autogenerated mock type for the CommentData type
type CommentData struct {
	mock.Mock
}

// Delete provides a mock function with given fields: commentID
func (_m *CommentData) Delete(commentID int) error {
	ret := _m.Called(commentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewComment provides a mock function with given fields: userID, newComment
func (_m *CommentData) NewComment(userID int, newComment comment.Core) (comment.Core, error) {
	ret := _m.Called(userID, newComment)

	var r0 comment.Core
	if rf, ok := ret.Get(0).(func(int, comment.Core) comment.Core); ok {
		r0 = rf(userID, newComment)
	} else {
		r0 = ret.Get(0).(comment.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, comment.Core) error); ok {
		r1 = rf(userID, newComment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCommentData interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommentData creates a new instance of CommentData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommentData(t mockConstructorTestingTNewCommentData) *CommentData {
	mock := &CommentData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
