// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	contents "sosmedapps/features/contents"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// ContentService is an autogenerated mock type for the ContentService type
type ContentService struct {
	mock.Mock
}

// AddContent provides a mock function with given fields: token, fileHeader, newContent
func (_m *ContentService) AddContent(token interface{}, fileHeader multipart.FileHeader, newContent contents.CoreContent) (contents.CoreContent, error) {
	ret := _m.Called(token, fileHeader, newContent)

	var r0 contents.CoreContent
	if rf, ok := ret.Get(0).(func(interface{}, multipart.FileHeader, contents.CoreContent) contents.CoreContent); ok {
		r0 = rf(token, fileHeader, newContent)
	} else {
		r0 = ret.Get(0).(contents.CoreContent)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, multipart.FileHeader, contents.CoreContent) error); ok {
		r1 = rf(token, fileHeader, newContent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllContent provides a mock function with given fields:
func (_m *ContentService) AllContent() ([]contents.CoreContent, error) {
	ret := _m.Called()

	var r0 []contents.CoreContent
	if rf, ok := ret.Get(0).(func() []contents.CoreContent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contents.CoreContent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewContentService interface {
	mock.TestingT
	Cleanup(func())
}

// NewContentService creates a new instance of ContentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewContentService(t mockConstructorTestingTNewContentService) *ContentService {
	mock := &ContentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
